theBasics(); separator()
basicOperators(); separator()
basicText(); separator()
collectionTypes(); separator()
controlFlow(); separator()
functions(); separator()
closures(); separator()
enumerations(); separator()
structuresAndClasses(); separator()
optionalChain(); separator()
errorHandling(); separator()
typeCasting(); separator()
extensions(); separator()
protocols(); separator()
generics(); separator()
opaqueTypes(); separator()
advancedOperators(); separator()
dependencies(); separator()

private func separator() {
    print( "================================================================================" )
}
